###########################################
# CN-CIDR4 for Surge                      #
# Last Updated: 2025-05-19T04:24:13Z      #
#                                         #
# Data source: gaoyifan/china-operator-ip #
###########################################
