name: Build

on:
  schedule:
    - cron: '0 4 * * *'
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  gen:
    runs-on: ubuntu-latest
    steps:
    - name: Download file
      run: |
        curl -s -o ipv4-org.conf "https://raw.githubusercontent.com/gaoyifan/china-operator-ip/ip-lists/china.txt"
        curl -s -o ipv6-org.conf "https://raw.githubusercontent.com/gaoyifan/china-operator-ip/ip-lists/china6.txt"

    - name: Prefix ipv4-org.conf
      run: sed -i 's/^/IP-CIDR,/' ipv4-org.conf

    - name: Prefix ipv6-org.conf
      run: sed -i 's/^/IP-CIDR6,/' ipv6-org.conf

    - name: Generate ipv4.conf
      run: |
        echo '###########################################' >> ipv4.conf
        echo '# CN-CIDR4 for Surge                      #' >> ipv4.conf
        echo "# Last Updated: $(date +'%FT%TZ')      #" >> ipv4.conf
        echo '#                                         #' >> ipv4.conf
        echo '# Data source: gaoyifan/china-operator-ip #' >> ipv4.conf
        echo '###########################################' >> ipv4.conf
        cat ipv4-org.conf >> ipv4.conf

    - name: Generate ipv6.conf
      run: |
        echo '###########################################' >> ipv6.conf
        echo '# CN-CIDR6 for Surge                      #' >> ipv6.conf
        echo "# Last Updated: $(date +'%FT%TZ')      #" >> ipv6.conf
        echo '#                                         #' >> ipv6.conf
        echo '# Data source: gaoyifan/china-operator-ip #' >> ipv6.conf
        echo '###########################################' >> ipv6.conf
        cat ipv6-org.conf >> ipv6.conf

    - name: Generate ip.conf
      run: |
        echo '###########################################' >> ip.conf
        echo '# CN-CIDR for Surge                       #' >> ip.conf
        echo "# Last Updated: $(date +'%FT%TZ')      #" >> ip.conf
        echo '#                                         #' >> ip.conf
        echo '# Data source: gaoyifan/china-operator-ip #' >> ip.conf
        echo '###########################################' >> ip.conf
        cat ipv4-org.conf >> ip.conf
        cat ipv6-org.conf >> ip.conf

    - name: Remove unused files && Check files
      run: |
        rm -f ipv4-org.conf ipv6-org.conf

    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ref: ip-lists
        fetch-depth: 0

    - name: Commit file
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add .
        git checkout -b ip-lists
        git commit -m "Update $(date +'%Y-%m-%d')"
        git push origin HEAD:ip-lists
